apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-expense-tracker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: room-expense-tracker

  template:
    metadata:
      labels:
        app: room-expense-tracker

    spec:
      containers:
        - name: room-expense-tracker
          image: ghcr.io/yasinshaik07/room-expense-tracker:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: roomapp-secret
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: roomapp-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roomapp-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: room-expense-tracker-service

spec:
  selector:
    app: room-expense-tracker

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: LoadBalancer