name: Java CI with Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Give Maven Permission
        run: chmod +x mvnw

      - name: Build Project
        run: ./mvnw clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t room-expense-tracker .